version: 0.2

phases:

  build:
    commands:
      - npm install
  build:
    commands:
      - docker build -t docker-react-app .

  post_build:
    commands:
      - docker run docker-react-app npm run test
      - docker images

