version: 0.2

phases:

  pre_build:
    commands:
      - sudo service docker start
      - docker build -t docker-react-app .

  build:
    commands:
      - docker run docker-react-app npm run test --coverage
  
